version: "3"

services:
  proxy:
    build:
      context: ./
    ports:
      - 8080:8080
    environment:
      STATIC_PAGES_HOST: static.futurelearn.com
      PORT: 8080
      BACKEND_HOST: nginx
      API_SERVER_NAME: test.com

  nginx:
    image: nginx
    ports:
      - 80:80
