version: "3"

services:
  proxy:
    build:
      context: ./
    ports:
      - 80:80
    environment:
      API_SERVER_NAME: ${API_SERVER_NAME}
      STATIC_PAGES_BUCKET: ${STATIC_PAGES_BUCKET} # Set in .env file
      MAINTENANCE_MODE: "true"
