version: "3"

services:
  proxy:
    build:
      context: ./
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      BACKEND_HOST: nginx
      STATIC_PAGES_BUCKET: ${STATIC_PAGES_BUCKET} # set in .env file

  nginx:
    image: nginx
    ports:
      - 80:80
