pipeline:
  lint:
    image: projectatomic/dockerfile-lint
    commands:
      - dockerfile_lint -f futurelearn-drone/Dockerfile
      - dockerfile_lint -f futurelearn-ruby/Dockerfile
      - dockerfile_lint -f warehouse-drone/Dockerfile

  notify:
    image: plugins/slack
    channel: notifications
    secrets: [ slack_webhook ]
    when:
     status: [ success, failure ]
