pipeline:
  lint:
    image: projectatomic/dockerfile-lint
    commands:
      - dockerfile_lint -f futurelearn-drone/Dockerfile

  docker-build:
    image: plugins/docker
    repo: futurelearn/futurelearn-drone
    dockerfile: futurelearn-drone/Dockerfile
    tags:
      - latest
      - $$BRANCH
    secrets: [ docker_username, docker_password ]

  notify:
    image: plugins/slack
    channel: drone-notifications
    secrets: [ slack_webhook ]
    when:
     status: [ success, failure ]
