pipeline:
  lint:
    image: projectatomic/dockerfile-lint
    commands:
      - dockerfile_lint -f futurelearn-drone/Dockerfile
      - dockerfile_lint -f futurelearn-ruby/Dockerfile
      - dockerfile_lint -f warehouse-drone/Dockerfile

  futurelearn-drone publish:
    group: publish
    image: plugins/docker
    repo: futurelearn/futurelearn-drone
    dockerfile: futurelearn-drone/Dockerfile
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  futurelearn-ruby publish:
    group: publish
    image: plugins/docker
    repo: futurelearn/futurelearn-ruby
    dockerfile: futurelearn-ruby/Dockerfile
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
      - 2.5.1
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  warehouse-drone publish:
    group: publish
    image: plugins/docker
    repo: futurelearn/warehouse-drone
    dockerfile: warehouse-drone/Dockerfile
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  terraform-drone publish:
    group: publish
    image: plugins/docker
    repo: futurelearn/terraform-drone
    dockerfile: terraform-drone/Dockerfile
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  notify:
    image: plugins/slack
    channel: drone-notifications
    secrets: [ slack_webhook ]
    when:
     status: [ success, failure ]
