pipeline:
  lint:
    image: projectatomic/dockerfile-lint
    commands:
      - dockerfile_lint -f futurelearn-drone/Dockerfile
      - dockerfile_lint -f futurelearn-ruby/Dockerfile
      - dockerfile_lint -f warehouse-drone/Dockerfile

  futurelearn-drone publish:
    group: publish
    image: plugins/docker
    repo: futurelearn/futurelearn-drone
    dockerfile: futurelearn-drone/Dockerfile
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
      - 2.5.3
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  futurelearn-drone publish ecr:
    group: publish
    image: plugins/ecr
    settings:
      repo: 695769953266.dkr.ecr.eu-west-1.amazonaws.com/futurelearn-drone
      registry: 695769953266.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: futurelearn-drone/Dockerfile
      tags:
        - sc-testing-ecr
    when:
      branch: sc-push-to-ecr

  futurelearn-ruby publish:
    group: publish
    image: plugins/docker
    repo: futurelearn/futurelearn-ruby
    dockerfile: futurelearn-ruby/Dockerfile
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
      - 2.5.3
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  warehouse-drone publish:
    group: publish
    image: plugins/docker
    repo: futurelearn/warehouse-drone
    dockerfile: warehouse-drone/Dockerfile
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
      - 2.5.3
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  terraform-drone publish:
    group: publish
    image: plugins/docker
    repo: futurelearn/terraform-drone
    dockerfile: terraform-drone/Dockerfile
    tags:
      - latest
      - "${DRONE_BUILD_NUMBER}"
      - 2.5.3
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  notify:
    image: plugins/slack
    channel: notifications
    secrets: [ slack_webhook ]
    when:
     status: [ success, failure ]
