entryPoints:
  backend:
    address: :${PORT}

providers:
  file:
    filename: /etc/traefik/traefik.yaml

log:
  level: ${LOG_LEVEL}
  format: json

http:
  routers:
    default:
      service: backend
      rule: "HostRegexp(`{wildcard:.*}`)"
      middlewares:
        - errors
        - headers
  services:
    backend:
      loadBalancer:
        servers:
          - url: ${BACKEND_HOST}
    errors:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: ${STATIC_PAGES_HOST}
  middlewares:
    # one middleware can't do multiple types so must be specified separately
    errors:
      errors:
        status:
          - "400"
          - "404"
          - "413"
          - "422"
          - "500"
          - "502"
          - "503"
        service: errors
        query: "/errors/{status}.html"
    headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: https
